### ISSUE TITLE
Most popular

### ISSUE THREAD

**Issue by onemanstartup** [rasguanabana/ytfs#14]
Is it possible to make search based on views without searching in channels? I don't know if youtube api has this possibility.

**Comment by rasguanabana** [comment]
Yes, youtube api allows you to do that. Ordering by relevance is the default one. I'll add the option soon with some bigger changes in a week or so.

**Comment by onemanstartup** [comment]
Oh, yes, i finally found that in api you can omit query term. In browser you just can't find most viewed videos
