### ISSUE TITLE
can't do anything with the files. 'bad address'

### ISSUE THREAD

**Issue by vladiibine** [rasguanabana/ytfs#15]
I tried to save a vid, with the command

`cp vid /tmp`

Got this: `cp: cannot open ‘morality.mp4’ for reading: Bad address`
Also the mplayer example won't work, and the the vlc player also tells me `filesystem access error: cannot open file /tmp/ytfs/something/somethig (Bad address)` .

Also when mounting the system, I got this message, but creating directories seemed to work ok: 'fusermount: failed to open /etc/fuse.conf: Permission denied'.

I have some strace output, i think the relevant one is here:

```
stat("the_file.mp4", {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
stat("/tmp/the_file.mp4", 0x7ffdbc0d0de0) = -1 ENOENT (No such file or directory)
open("the_file.mp4", O_RDONLY) = -1 EFAULT (Bad address)
```

So if you need any more info from me, I'll happily provide it. In the meantime I might take a look for myself, and I'll post here if I find something.

**Comment by rasguanabana** [comment]
Thank you for reporting. Please check if last commit fixed the problem.

**Comment by vladiibine** [comment]
Nope. Still there. Still the same.

**Comment by rasguanabana** [comment]
Please run ytfs with `-d` (debug) option and show output after failure.
