### ISSUE TITLE
Add syntax for channels/users

### ISSUE THREAD

**Issue by diafygi** [rasguanabana/ytfs#2]
It would be great to add folders for specific youtubers. That way, I can just have my list of users I subscribe to in directory format. Perhaps having similar syntax to google's site:example.com syntax?

```
larry@localhost /tmp/ytfs $ mkdir user:zisteau
```

**Comment by rasguanabana** [comment]
Should appear in next commit along with preferred format selection and some other options.
Also, I'm planning to implement playlist support in near future, just have to think about how :)
