### ISSUE TITLE
Mount point doesn't show over SMB share.

### ISSUE THREAD

**Issue by beigexperience** [rasguanabana/ytfs#24]
The folder in which the ytfs mount is located doesn't even show up in a samba share. 

Symlinks to the folder also don't show up. 

---

edit: 

Problem seems to be fixed by changing: 
    FUSE(YTFS(), x.mountpoint[0], foreground=x.d)
to
    FUSE(YTFS(), x.mountpoint[0], foreground=x.d, allow_other=True)

I also had to add "user_allow_other" to /etc/fuse.conf.

**Comment by rasguanabana** [comment]
Thanks for noticing this. Committed fix.
BTW, does samba share work well with ytfs?

**Comment by beigexperience** [comment]
It sort of works but it seems to hang some windows programs sometimes, not
sure why.

edit: works fine if you use -P. I'm using ytfs and a smb share from a virtualbox vm on a windows host and it works fine.

**Comment by rasguanabana** [comment]
Thanks for info. Hangs are most likely caused by waiting for read system calls. This should improve with replacing current really dumb caching with something better.
