### ISSUE TITLE
Channel: searching

### ISSUE THREAD

**Issue by beigexperience** [rasguanabana/ytfs#25]
Windows forbids the characters \ / : \* ? " < > |  from appearing in folder/file names. 

So searching by "channel:channel_name" will not work. Can you provide a switch for a different delimiter?

**Comment by rasguanabana** [comment]
I think mount option is too much for a setting this small, but it definitely should be possible with config file, which isn't yet implemented. As for now I'll modify parser to recognise `=` as delimeter (interchangeably with `:`)
Seems like I completely forgot about forbidden characters across various systems. I only did changing `/` to `\` when a video title contains a slash, but I guess it will fail on Windows anyway. Thanks for pointing this out.
