### ISSUE TITLE
Same thing as Steam bug in makefile's "clean"

### ISSUE THREAD

**Issue by ijustlovemath** [rasguanabana/ytfs#3]
https://github.com/rasguanabana/ytfs/blob/master/doc/Makefile#L52

If, for whatever reason, the BUILDDIR env. is not set, this will evaluate to rm -rf /\* for the current user, erasing all files owned by that user. Check this out for more info: http://www.extremetech.com/extreme/197686-nasty-steam-for-linux-bug-can-wipe-all-your-user-files

**Comment by rasguanabana** [comment]
Thanks for paying attention! This looks like Sphinx problem, so please make an issue there.
