### ISSUE TITLE
What dependency am I missing?

### ISSUE THREAD

**Issue by eamrhein** [rasguanabana/ytfs#4]
## Solved

python versioning issue;

**Comment by TingPing** [comment]
https://ytfs.readthedocs.org/en/latest/dependencies.html

**Comment by m0veax** [comment]
https://github.com/terencehonles/fusepy

**Comment by eamrhein** [comment]
When I do **sudo pip install fusepy** it says it's already installed. youtube-dl is installed, Fuse is installed, Fmpeg/Libav are installed, Requests is installed. Not sure whats left unless they need to be installed locally instead of globally.
