### ISSUE TITLE
Description in .txt files

### ISSUE THREAD

**Issue by errge** [rasguanabana/ytfs#9]
I don't know the YouTube API or youtube-dl at all, but would it be possible to have beside the .mp4 files .txt files with the video description?  Sometimes it's really useful to read them as they contain important info, links, lyrics, etc...

**Comment by rasguanabana** [comment]
I realise that it's inconvenient to browse files without thumbnails and descriptions, but I can't find a sensible way to implement them. Main problems:
- Description files for every movie would clutter search directory
- It takes some effort for user - one needs to open another file separately, with seperate program.
- There's no simple way to associate movie with its description, maybe some players support it, but are there any standards?

The only reasonable solution I can think of is providing a single file, which contains info about files currently being opened. User could either read the file herself, or feed it to another program (conky, notification managers, etc.)

I'm open to any suggestions, though :) It's just my opinion.

**Comment by errge** [comment]
Hi,

I mainly plan to use YTFS from the command line.  So my usage pattern
is "mplayer some_result.avi" and therefore "cat some_result.txt" is
not unreasonable or uncomfortable at all.

I also don't buy the cluttering argument, since command line guys are
fine anyway ("ls *mp4", "ls *txt", etc.) while graphical movie players
will only show the correct extensions anyway in the open dialog, so
Average Joe is fine too.

And thumbnails are a great idea, that should be there in *png or
*jpg.

I undestand your points and problem statements, but I don't think
those are great arguments for not providing this feature which would
help a lot for the power users.  Maybe make it an option and then
people can enable/disable it.  It's even OK for me if it's disabled by
default.

The next/prev hack that you provide for stepping in search results is
also not an industry standard by any shot, but it still works great
and it's a good use of the filesystem layer.

If you really object all this new files and the clutter, then you can
provide everything in extended attributes and then people use the
"getfattr" tool to read those.

http://stackoverflow.com/questions/16045921/fuse-extended-attributes

Maybe that is the right way of doing it.  Then you can even export
attributes like duration, youtube video id, likes, views, etc.  Sounds
pretty cool!

Gergely

**Comment by rasguanabana** [comment]
Maybe you're right. Making it an option sounds like the best solution, it won't hurt anybody.

edit: Also, integration with semantic desktops might be nice.
